package Backend.ElectionVote.enums;


public enum ActivityType {
    LOGIN,
    LOGOUT,
    SUBMISSION_CREATE,
    SUBMISSION_VERIFY,
    SUBMISSION_REJECT,
    TALLY_UPLOAD,
    OBSERVER_REPORT_CREATE,
    OBSERVER_REPORT_RESOLVE,
    USER_CREATE,
    USER_DISABLE,
    USER_ENABLE,
    SETTINGS_UPDATE,
    CREATE,
    UPDATE,
    DELETE,
    APPROVE,
    REJECT,
    UPLOAD,
    EXPORT,
    VERIFY,
    OTHER
}