spring.application.name=ElectionVote

# --- PostgreSQL connection ---
spring.datasource.url=jdbc:postgresql://localhost:5432/election_vote_tracker
spring.datasource.username=postgres
spring.datasource.password=romelta2

# Optional (Boot usually detects it)
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA ---
# we?ll run your SQL ourselves
spring.jpa.hibernate.ddl-auto=none

# see queries in console (dev-only)
spring.jpa.show-sql=true

# Keep logs quiet (optional)
logging.level.org.hibernate.SQL=warn
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=warn

